version: '3.9'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.pg
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - /srv/postgres_data:/var/lib/postgresql/data
    networks:
      - ajos-network

  init-db:
    build:
      context: ./db
      dockerfile: Dockerfile.pg
    depends_on:
      - db
    env_file:
      - ./db/.env
    entrypoint: >
      sh -c '
        until pg_isready -h db -U "$POSTGRES_USER"; do
          echo "Waiting for Postgres…" && sleep 2;
        done;
        psql -h db -U postgres -c "CREATE DATABASE $POSTGRES_DB;" || true;
        psql -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -c "CREATE EXTENSION IF NOT EXISTS postgis;" \
          -c "CREATE EXTENSION IF NOT EXISTS vector;"
      '
    networks:
      - ajos-network

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    networks:
      - ajos-network

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    command: ["streamlit", "run", "Home.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    networks:
      - ajos-network

networks:
  ajos-network:
    driver: bridge
