version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "5488:5432"
    volumes:
      - /srv/postgres_data:/var/lib/postgresql/data
    networks:
      - ajos-network

  init-db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    depends_on:
      - db
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    entrypoint: >
      sh -c '
        until pg_isready -h db -U "$POSTGRES_USER"; do
          echo "Waiting for Postgres…" && sleep 2;
        done;
        psql -h db -U postgres -c "CREATE DATABASE $POSTGRES_DB;" || true;
        psql -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -c "CREATE EXTENSION IF NOT EXISTS postgis;" \
          -c "CREATE EXTENSION IF NOT EXISTS vector;"
      '
    networks:
      - ajos-network

networks:
  ajos-network:
    driver: bridge
